// <auto-generated />
namespace Course_Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BS_Student_AddColumn_Active : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BS_Student_AddColumn_Active));
        
        string IMigrationMetadata.Id
        {
            get { return "202104111435465_BS_Student_AddColumn_Active"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
